version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: fintech-mysql
    environment:
      MYSQL_ROOT_PASSWORD: fintech1234
      MYSQL_DATABASE: fintech_db
      MYSQL_USER: fintech
      MYSQL_PASSWORD: fintech1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: fintech-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: